version: '3'
services:
  redpanda1:
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 3
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    privileged: true
    container_name: redpanda1
    hostname: redpanda1
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/redpanda1/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
  redpanda2:
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 3
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: redpanda2
    hostname: redpanda2
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/redpanda2/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
  redpanda3:
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 3
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: redpanda3
    hostname: redpanda3
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/redpanda3/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
  client1:
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 3
      context: .
      dockerfile: ./docker/client/Dockerfile
    depends_on:
      - "redpanda1"
      - "redpanda2"
      - "redpanda3"
    privileged: true
    container_name: client1
    hostname: client1
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/client1/mnt/vectorized/workloads/logs:/mnt/vectorized/workloads/logs
  control:
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 3
      context: .
      dockerfile: ./docker/control/Dockerfile
    depends_on:
      - "redpanda1"
      - "redpanda2"
      - "redpanda3"
      - "client1"
    privileged: true
    container_name: control
    hostname: control
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/control/mnt/vectorized/experiments:/mnt/vectorized/experiments
networks:
  chaos:
    driver: bridge